# Generated by Django 3.2.8 on 2021-11-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addgroup', '__first__'),
        ('group_details', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_delivery', models.DateField(auto_now_add=True)),
                ('add_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addgroup.group_list')),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group_details.delivaries')),
            ],
        ),
    ]
