# Generated by Django 3.2.9 on 2021-11-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='add_group',
        ),
    ]
