# Generated by Django 3.2.8 on 2021-11-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addgroup', '0002_alter_group_list_group_name'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='add_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addgroup.group_list'),
        ),
    ]
