# Generated by Django 3.2.8 on 2021-11-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0012_auto_20211110_1038'),
        ('payments', '0002_payments_add_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group_details.delivaries'),
        ),
    ]
