# Generated by Django 3.2.9 on 2021-11-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addgroup', '0001_initial'),
        ('payments', '0002_remove_payments_add_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='add_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addgroup.group_list'),
        ),
    ]
