# Generated by Django 3.2.8 on 2021-11-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payments_add_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Rejected', 'Rejected')], default='Unpaid', max_length=200, null=True),
        ),
    ]
