# Generated by Django 3.2.9 on 2021-11-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20211118_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=300, null=True)),
                ('pay_bill', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payments',
            name='pay_bill',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='phone_number',
        ),
    ]
