# Generated by Django 3.2.8 on 2021-11-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payments_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=200, null=True),
        ),
    ]
