# Generated by Django 3.2.9 on 2021-11-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20211118_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipa',
            name='amount_paid',
            field=models.BigIntegerField(null=True),
        ),
    ]
