# Generated by Django 3.2.9 on 2021-11-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payments_payment_status'),
        ('payments', '0006_lipa_amount_paid'),
    ]

    operations = [
    ]
