# Generated by Django 3.2.8 on 2021-10-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_list',
            fields=[
                ('group_name', models.CharField(max_length=100)),
                ('number_of_group_members', models.PositiveSmallIntegerField()),
                ('profile', models.ImageField(default='default.jpg', null=True, upload_to='profile_images')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
