# Generated by Django 3.2.4 on 2021-11-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addgroup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_list',
            old_name='number_of_group_members',
            new_name='no_of_members',
        ),
    ]
