# Generated by Django 3.2.9 on 2021-11-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addgroup', '0002_alter_group_list_group_name'),
        ('addgroup', '0002_group_list_payment_status'),
    ]

    operations = [
    ]
