# Generated by Django 3.2.8 on 2021-11-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0003_alter_group_details_price_per_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_details',
            name='total_quantity_purchased',
        ),
        migrations.AlterField(
            model_name='group_details',
            name='total_amount',
            field=models.BigIntegerField(max_length=20, null=True),
        ),
    ]
