# Generated by Django 3.2.8 on 2021-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0005_alter_group_details_kgs_of_beans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_details',
            name='total_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
