# Generated by Django 3.2.8 on 2021-11-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('Iwacu group', 'Iwacu group'), ('Komera cooperative', 'Komera cooperative'), ('Ubwiyunge cooperative', 'Ubwiyunge cooperative')], max_length=200, null=True)),
                ('beans_variety', models.CharField(choices=[('Bush Beans', 'Bush Beans'), ('Climbing Beans', 'Climbing Beans'), ('Ruvuninkingi', 'Ruvuninkingi')], max_length=800, null=True)),
                ('date_of_delivery', models.DateTimeField(null=True)),
                ('kgs_of_beans', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
