# Generated by Django 3.2.8 on 2021-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('Iwacu group', 'Iwacu group'), ('Komera cooperative', 'Komera cooperative'), ('Ubwiyunge cooperative', 'Ubwiyunge cooperative')], max_length=200, null=True)),
                ('date_of_delivery', models.DateTimeField(null=True)),
                ('beans_variety', models.CharField(choices=[('Bush beans', 'Bush beans'), ('Climbing beans', 'Climbing beans'), ('Ruvuninkingi', 'Ruvuninkingi')], max_length=200, null=True)),
                ('kgs_of_beans', models.PositiveSmallIntegerField(null=True)),
                ('price_per_kg', models.PositiveSmallIntegerField(null=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Rejected', 'Rejected')], max_length=90, null=True)),
            ],
        ),
    ]
