# Generated by Django 3.2.8 on 2021-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_delivery', models.DateField(null=True)),
                ('beans_variety', models.CharField(choices=[('Bush Beans', 'Bush Beans'), ('Climbing Beans', 'Climbing Beans'), ('Ruvuninkingi', 'Ruvuninkingi')], max_length=800, null=True)),
                ('group_name', models.CharField(max_length=120, null=True)),
                ('kgs_of_beans', models.PositiveSmallIntegerField(null=True)),
                ('Price_per_kg', models.DateField(null=True)),
                ('total_amount', models.CharField(max_length=20, null=True)),
                ('total_quantity_purchased', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bean_details',
        ),
    ]
