# Generated by Django 3.2.8 on 2021-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_details',
            name='number_of_group_members',
        ),
        migrations.AddField(
            model_name='group_details',
            name='Price_per_kg',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group_details',
            name='beans_variety',
            field=models.CharField(choices=[('Bush Beans', 'Bush Beans'), ('Climbing Beans', 'Climbing Beans'), ('Ruvuninkingi', 'Ruvuninkingi')], max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='group_details',
            name='date_of_delivery',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='group_details',
            name='kgs_of_beans',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group_details',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='group_details',
            name='total_amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group_details',
            name='total_quantity_purchased',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group_details',
            name='group_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
