# Generated by Django 3.2.8 on 2021-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bean_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beans_variety', models.CharField(choices=[('Bush Beans', 'Bush Beans'), ('Climbing Beans', 'Climbing Beans'), ('Ruvuninkingi', 'Ruvuninkingi')], max_length=800, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='delivaries',
            name='beans_variety',
        ),
    ]
