# Generated by Django 3.2.9 on 2021-11-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addgroup', '0001_initial'),
        ('group_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivaries',
            name='group_name',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='addgroup.group_list'),
        ),
    ]
