# Generated by Django 3.2.8 on 2021-10-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0002_auto_20211031_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_details',
            name='total_quantity_purchased',
        ),
    ]
