# Generated by Django 3.2.8 on 2021-11-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('group_details', '0002_auto_20211108_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean_details',
            name='beans_variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payments'),
        ),
    ]
