# Generated by Django 3.2.8 on 2021-11-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0002_remove_group_details_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_details',
            name='total_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
