# Generated by Django 3.2.9 on 2021-11-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0002_alter_delivaries_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivaries',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Rejected', 'Rejected')], max_length=200, null=True),
        ),
    ]
