# Generated by Django 3.2.8 on 2021-11-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0002_auto_20211031_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_details',
            name='Price_per_kg',
            field=models.BigIntegerField(null=True),
        ),
    ]
