# Generated by Django 3.2.8 on 2021-11-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0003_remove_group_details_total_quantity_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_details',
            name='Price_per_kg',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group_details',
            name='date_of_delivery',
            field=models.DateTimeField(null=True),
        ),
    ]
