# Generated by Django 3.2.8 on 2021-11-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0004_auto_20211101_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_details',
            name='kgs_of_beans',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
