# Generated by Django 3.2.8 on 2021-11-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0004_rename_status_delivaries_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivaries',
            name='date_of_delivery',
        ),
        migrations.AddField(
            model_name='delivaries',
            name='date_delivaries',
            field=models.DateField(null=True),
        ),
    ]
