# Generated by Django 3.2.8 on 2021-11-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0008_alter_bean_details_beans_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean_details',
            name='price_per_kg',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
