# Generated by Django 3.2.8 on 2021-11-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0009_bean_details_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean_details',
            name='price_per_kg',
            field=models.TextField(null=True),
        ),
    ]
