# Generated by Django 3.2.8 on 2021-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0011_alter_bean_details_price_per_kg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bean_details',
        ),
        migrations.AddField(
            model_name='delivaries',
            name='beans_variety',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delivaries',
            name='price_per_kg',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
