# Generated by Django 3.2.8 on 2021-11-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0012_auto_20211110_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivaries',
            name='group_name',
        ),
    ]
