# Generated by Django 3.2.8 on 2021-11-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0013_auto_20211111_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivaries',
            name='group_name',
            field=models.CharField(choices=[('Iwacu group', 'Iwacu group'), ('Komera cooperative', 'Komera cooperative'), ('Ubwiyunge cooperative', 'Ubwiyunge cooperative')], max_length=200, null=True),
        ),
    ]
