# Generated by Django 3.2.8 on 2021-11-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addgroup', '0002_alter_group_list_group_name'),
        ('group_details', '0014_alter_delivaries_beans_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivaries',
            name='details',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='addgroup.group_list'),
            preserve_default=False,
        ),
    ]
