# Generated by Django 3.2.8 on 2021-11-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addgroup', '0002_alter_group_list_group_name'),
        ('group_details', '0016_remove_delivaries_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivaries',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addgroup.group_list'),
        ),
    ]
