# Generated by Django 3.2.8 on 2021-11-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0017_delivaries_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivaries',
            old_name='groups',
            new_name='group',
        ),
    ]
