# Generated by Django 3.2.8 on 2021-11-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0018_rename_groups_delivaries_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivaries',
            name='group',
        ),
        migrations.AddField(
            model_name='delivaries',
            name='group_name',
            field=models.CharField(choices=[('Iwacu group', 'Iwacu group'), ('Komera cooperative', 'Komera cooperative'), ('Ubwiyunge cooperative', 'Ubwiyunge cooperative')], max_length=200, null=True),
        ),
    ]
