# Generated by Django 3.2.8 on 2021-11-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_details', '0015_delivaries_status'),
        ('group_details', '0019_auto_20211112_1013'),
    ]

    operations = [
    ]
