# Generated by Django 3.2.9 on 2021-11-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_page',
            name='message',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='setting_page',
            name='search',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
