# Generated by Django 3.2.8 on 2021-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_page',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='setting_page',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
