# Generated by Django 3.2.4 on 2021-11-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_page',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
