# Generated by Django 3.2.8 on 2021-11-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20211108_1259'),
        ('settings', '0002_auto_20211109_1214'),
    ]

    operations = [
    ]
