# Generated by Django 3.2.8 on 2021-11-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_merge_0002_auto_20211108_1259_0002_auto_20211109_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting_page',
            name='avatar',
        ),
    ]
