# Generated by Django 3.2.8 on 2021-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20211103_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_page',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/avatars/', verbose_name='profile picture'),
        ),
    ]
