# Generated by Django 3.2.8 on 2021-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_setting_page_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_page',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
