# Generated by Django 3.2.4 on 2021-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('no_of_group_member', models.PositiveSmallIntegerField(null=True)),
                ('group_leader_contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
